= NI-KOP, 4. úkol

Jan Bittner (bittnja3)

== Zadání úlohy

Úkolem je prozkoumat citlivost metod řešení problému batohu na parametry instancí -- poměru kapacity batohu k sumární váze; korelaci cena/váha; rozložení vah a granualitu.

== Použité prostředky

=== Programovací jazyky a software

Úloha byla řešena v jazyce C++ na operačním systému Windows 10.

Měření bylo spuštěno z *Bashe* prostřednictvím prostředí WSL 2 (*Windows Subsystem for Linux 2*), které využívá *Ubuntu 20.04.1 LTS*, nebylo tedy pro spuštění použito IDE.

Na zachycení aktuálního času bylo využito `std::chrono::high_resolution_clock::now()`.

=== Konfigurace testovacího stroje

Testování bylo provedeno na *Legion 5 15ARH05H*. Stroj obsahuje CPU *AMD Ryzen 7 4800H @ 2.90 GHz* a RAM *DDR4 16.00 GB*.

== Rozbor možných variant řešení

== Rámcový popis postupu řešení

== Popis kostry algoritmu

== Naměřené výsledky

1. mutation 10, cross 35 (200)

=== Parametr maximální váhy

== Závěr

Z naměřených dat, jak je vidět z grafů, lze usoudit, že výpočetní složitost metod bf, bnb ani dyn nejsou závislé na změně parametru maximální váhy. To je očekávané chování vůči znalosti jak algoritmy fungují.

Z grafů jde vidět, že výpočetní složitost metody dynamického programování je závislá na parametru maximální ceny. To souhlasí se stanoveným předpokladem, jelikož doba běhu algoritmu je přímo závislá na velikosti vyplňované tabulky. U metody hrubou silou a větví a hranic žádnou závislost na tomto parametru nepozoruji.

Při zkoumání závislosti výpočetní složitosti na parametru poměru kapacity batohu k sumární váze vidíme, že metoda větví a hranic je na tomto parametru závislá; dle předpokladu. Pro poměru kapacity a sumární váhy okolo hodnoty 0.4 je tento algoritmus nejpomalejší. Naopak s čím vyšší či čím nižší hodnotou se algoritmus zrychluje. To je způsobené právě vlivem ořezávání. U metod hrubou silou a dynamického programování žádnou závislost na tomto parametru nepozoruji.

Z grafů závislosti výpočetní složitosti na parametru korelace s váhou bylo zjištěno, že metody větví a hranic pro menší i silnou korelací s váhou pomalejší vyhodnocování. Dle měření se konstantně složitost zvýšila. U metody dynamického programování je pro silnou korelaci s váhou lehce pomalejší vyhodnocování.

Dle měření granularity zřejmě žádná výrazná závislost u metod hrubou silou, větví a hranic a dynamického programování není. Zdá se ale, že u všech metod je lehce pomalejší vyhodnocení při převaze lehkých či těžkých věcí. U metody dynamického programování je výpočet lehce pomalejší pro hodnotu exponentu kolem bodu 2.0, pro převahu lehkých i těžkých věcí. Pro metodu větví a hranic je výpočet lehce pomalejší kolem bodu 2.0 pro převahu těžkých věcí. Dle měření však nejde předpokládat obecně platná závislost.

Z meření relativní chyby heuristiky pro případ zkoumání parametru poměru kapacity batohu k sumární váze vyplývá, že chyba heuristiky klesá při vyšších hodnotách poměru. Pro nízké hodnoty může relativní chyba dosahovat hodnot okolo 35 %, proto pro ně není metoda vhodná. Naopak pro poměr nad 50 % má metoda relativní chybu zhruba pod 10 % a dále klesá pro vyšší hodnoty poměru. Pro vyšší hodnoty poměru je tedy metoda vhodná.

Z měření relativní chyby heuristiky pro případ zkoumání parametru exponentu granuality vidíme, že chyba mírně roste při vyšší granualitě, tedy při menším počtu malých věcí.

Z naměřených dat a dle jejich grafů nám tedy vyplývá, že metoda hrubé síly není závislá na parametrech (kromě počtů věcí v instanci), ale je nejpomalejší a tedy vhodná jen pro malé instance. Metoda větví a hranic je rychlá pro malé nebo velké poměry kapacity batoku k sumární váze. Metoda dynamického programování je rychlá, ale je závislá na váze předmětů a svou implementací spotřebovává velké množství paměti. Metoda je tedy vhodná zejména pro batohy s nízkými cenami. Heuristika je nejrychlejší metoda, avšak u speciálních batohů je možnost větších chyb. Metoda je nejvhodnější pro batohy s poměrem kapacity batohu k sumární váze blížící se hodnotě 1.
